Mojoras para el Board
rogeliosamuel621/Thrillo pull request #25
Opened 2021-01-10 21:19 UTC by senixcode

- Cambios al componente input 
- Nuevos Componentes
- Modificaciones Componentes
- Cambios en css

2021-01-12 23:54 UTC, rogeliosamuel621 requested changes
# Aún no hacer merge de este pr

- Se necesita cambiar la estructura del modal

Los cambios serán hechos por @rogeliosamuel621 para mas tardar hoy en la noche

2021-01-13 03:20 UTC, rogeliosamuel621 approved these changes

2021-01-13 17:27 UTC, senixcode commented
@rogeliosamuel621  solo hay errores de key en consola (es cuando haces un map en el componentes)

2021-01-13 18:24 UTC, rogeliosamuel621 commented
> @rogeliosamuel621 solo hay errores de key en consola (es cuando haces un map en el componentes)

Vale, lo revisaré

2021-01-13 21:43 UTC, merged